defaults:
  - _self_


#TODO: include run environment (pascal, neumann,... in the path)
hydra:
  run:
    dir: results/runs/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}

  sweep:
    dir: results/multirun/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}

  job:
    chdir: false

execution:
  phoenix_server_url: http://localhost:6006
  phoenix_graphql_url: http://localhost:4317
  model_backends: [ ] # To fill on startup
  backend_api_key_env_vars: { } # to fill on startup
  num_workers: 10
