execution:
  phoenix_server_url: http://localhost:6006
  phoenix_graphql_url: http://localhost:4317
  num_workers: 50


info:
  output_directory: /tmp # PLACEHOLDER - Added on Run

defaults:
  - experiment: null # has to be set on running hydra
  - _self_


hydra:
  run:
    dir: results/runs/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}

  sweep:
    dir: results/multirun/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}

  job:
    chdir: false