defaults:
  - _self_

hydra:
  run:
    dir: results/runs/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}

  sweep:
    dir: results/multirun/${experiment.name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}

  job:
    chdir: false

execution:
  phoenix_server_url: http://localhost:6006
  phoenix_graphql_url: http://localhost:4317
  num_workers: 50

meta_info: #  PLACEHOLDER - Added on Run
  output_directory: /tmp
  phoenix_project_name: "Not Set"

  execution:
    started_at_utc: "Unknown"        # ISO-8601 UTC timestamp
    argv: [ ]                         # CLI arguments used to start the run
    command: "Unknown"               # Full command string
  git:
    repo_root: null                  # Path to git repo root
    remote_url: null                 # Origin URL
    branch: null
    commit_sha: null
    commit_short_sha: null
    is_dirty: null                   # true / false / null if unknown
    diff_sha256: null                # Hash of git diff
    describe: null                   # git describe output
