slurm_config:
  time: 72:00:00
  cpus_per_task: 16
  memory_GB: 32
  partition: ampere

postgres:
  shared_buffers: 4GB
  work_mem: 128MB
  port: 15432
  sif_location_inside_project: assets/orchestration/postgres.sif

database_user: philipp.link

phoenix_sql_alchemy_pool_size: 30
phoenix_sql_alchemy_max_overflow: 40

ngingx_conf_location_inside_project: assets/orchestration/phoenix_nginx.conf
ngingx_sif_location_inside_project: assets/orchestration/nginx.sif


#changes need changes in assets/orchestration/phoenix_nginx.conf
port: 46001
graphql_port: 46318
phoenix_internal_graphql_ports:
  - 46319
  - 46320
  - 46321
  - 46322

phoenix_internal_ports:
  - 46002
  - 46003
  - 46004
  - 46005

