slurm_config:
  time: 48:00:00
  cpus_per_task: 16
  memory_GB: 128
  gres: gpu:1
  partition: ampere

llm_models:
  Qwen/Qwen2.5-0.5B-Instruct:
    port: 8000
  #    max_batch_prefill_tokens: 8193
  #    max_total_tokens: 8192
  #    max_input_tokens: 7168

  Qwen/Qwen3-0.6B:
    port: 40006
  Qwen/Qwen3-4B:
    port: 40004
  Qwen/Qwen3-14B:
    port: 40014

  Qwen/Qwen3.5-0.8B:
    port: 40508
  Qwen/Qwen3.5-4B:
    port: 40504
  Qwen/Qwen3.5-9B:
    port: 40509

  mistralai/Ministral-3-3B-Instruct-2512:
    port: 40253
  mistralai/Ministral-3-8B-Instruct-2512:
    port: 40258
    max_total_tokens: 150000 # to fit in VRAM
  mistralai/Ministral-3-14B-Instruct-2512:
    port: 40251
    max_total_tokens: 100000 # to fit in VRAM